import { CountryPermissionList } from "./permission";

export interface CountryData {
    id: number;
    lv: number;
    name: string;
    owner: string;
    lore: string;
    currencyUnitId: number;
    days: number;
    banner: string;
    colorcode: string;
    members: Array<string>;
    peaceChangeCooltime: number;
    ownerRole: number;
    adminRole: number;
    peopleRole: number;
    spawn: undefined | {};
    publicSpawn: boolean;
    roles: Array<number>;
    territories: Array<string>;
    resourcePoint: number;
    money: number;
    taxPer: number;
    taxInstitutionIsPer: boolean;
    hideMoney: boolean;
    peace: boolean;
    color: string;
    alliance: Array<number>;
    hostility: Array<number>;
    friendly: Array<number>;
    neutralityPermission: CountryPermissionList;
    alliancePermission: CountryPermissionList;
    hostilityPermission: CountryPermissionList;
    friendlyPermission: CountryPermissionList;
    internationalOrganizations: Array<number>;
    isWarNow: boolean;
    warNowCountries: Array<number>;
    declarationReceive: Array<number>;
    declarationSend: Array<number>;
    allianceRequestReceive: Array<number>;
    allianceRequestSend: Array<number>;
    friendlyRequestReceive: Array<number>;
    friendlyRequestSend: Array<number>;
    applicationPeaceRequestReceive: Array<number>;
    applicationPeaceRequestSend: Array<number>;
    invite: boolean;
    plotgroup: Array<number>;
    mergeRequestSend: Array<number>;
    mergeRequestReceive: Array<number>;
}