export default [
    {
        name: `建材`,
        lore: `building material`,
        icon: `minecraft:oak_log`,
        items: [
            { id: `minecraft:oak_log`, price: 4 },
            { id: `minecraft:acacia_log`, price: 4 },
            { id: `minecraft:birch_log`, price: 4 },
            { id: `minecraft:cherry_log`, price: 4 },
            { id: `minecraft:dark_oak_log`, price: 4 },
            { id: `minecraft:jungle_log`, price: 4 },
            { id: `minecraft:mangrove_log`, price: 4 },
            { id: `minecraft:spruce_log`, price: 4 },
            { id: `minecraft:pale_oak_log`, price: 4 },
            { id: `minecraft:white_concrete`, price: 4 },
            { id: `minecraft:light_gray_concrete`, price: 4 },
            { id: `minecraft:gray_concrete`, price: 4 },
            { id: `minecraft:black_concrete`, price: 4 },
            { id: `minecraft:brown_concrete`, price: 4 },
            { id: `minecraft:orange_concrete`, price: 4 },
            { id: `minecraft:red_concrete`, price: 4 },
            { id: `minecraft:yellow_concrete`, price: 4 },
            { id: `minecraft:lime_concrete`, price: 4 },
            { id: `minecraft:green_concrete`, price: 4 },
            { id: `minecraft:cyan_concrete`, price: 4 },
            { id: `minecraft:blue_concrete`, price: 4 },
            { id: `minecraft:light_blue_concrete`, price: 4 },
            { id: `minecraft:purple_concrete`, price: 4 },
            { id: `minecraft:magenta_concrete`, price: 4 },
            { id: `minecraft:pink_concrete`, price: 4 },
            { id: `minecraft:quartz_block`, price: 4 },
            { id: `minecraft:sandstone`, price: 4 },
            { id: `minecraft:brick_block`, price: 4 },
            { id: `minecraft:stonebrick`, price: 4 },
            { id: `minecraft:cobblestone`, price: 4 },
            { id: `minecraft:cobbled_deepslate`, price: 4 },
            { id: `minecraft:hardened_clay`, price: 4 },
            { id: `minecraft:white_terracotta`, price: 8 },
            { id: `minecraft:light_gray_terracotta`, price: 8 },
            { id: `minecraft:gray_terracotta`, price: 8 },
            { id: `minecraft:black_terracotta`, price: 8 },
            { id: `minecraft:brown_terracotta`, price: 8 },
            { id: `minecraft:red_terracotta`, price: 8 },
            { id: `minecraft:orange_terracotta`, price: 8 },
            { id: `minecraft:yellow_terracotta`, price: 8 },
            { id: `minecraft:lime_terracotta`, price: 8 },
            { id: `minecraft:green_terracotta`, price: 8 },
            { id: `minecraft:cyan_terracotta`, price: 8 },
            { id: `minecraft:light_blue_terracotta`, price: 8 },
            { id: `minecraft:blue_terracotta`, price: 8 },
            { id: `minecraft:purple_terracotta`, price: 8 },
            { id: `minecraft:magenta_terracotta`, price: 8 },
            { id: `minecraft:pink_terracotta`, price: 8 },
            { id: `minecraft:calcite`, price: 8 },
            { id: `minecraft:pale_moss_block`, price: 8 },
            { id: `minecraft:pale_hanging_moss`, price: 8 },
            { id: `minecraft:prismarine_bricks`, price: 8 },
            { id: `minecraft:white_wool`, price: 10 },
            { id: `minecraft:light_gray_wool`, price: 10 },
            { id: `minecraft:gray_wool`, price: 10 },
            { id: `minecraft:black_wool`, price: 10 },
            { id: `minecraft:brown_wool`, price: 10 },
            { id: `minecraft:red_wool`, price: 10 },
            { id: `minecraft:orange_wool`, price: 10 },
            { id: `minecraft:yellow_wool`, price: 10 },
            { id: `minecraft:lime_wool`, price: 10 },
            { id: `minecraft:green_wool`, price: 10 },
            { id: `minecraft:cyan_wool`, price: 10 },
            { id: `minecraft:light_blue_wool`, price: 10 },
            { id: `minecraft:blue_wool`, price: 10 },
            { id: `minecraft:purple_wool`, price: 10 },
            { id: `minecraft:magenta_wool`, price: 10 },
            { id: `minecraft:pink_wool`, price: 10 },
            { id: `minecraft:gravel`, price: 8 },
            { id: `minecraft:white_concrete_powder`, price: 4 },
            { id: `minecraft:light_gray_concrete_powder`, price: 4 },
            { id: `minecraft:gray_concrete_powder`, price: 4 },
            { id: `minecraft:black_concrete_powder`, price: 4 },
            { id: `minecraft:brown_concrete_powder`, price: 4 },
            { id: `minecraft:red_concrete_powder`, price: 4 },
            { id: `minecraft:orange_concrete_powder`, price: 4 },
            { id: `minecraft:yellow_concrete_powder`, price: 4 },
            { id: `minecraft:lime_concrete_powder`, price: 4 },
            { id: `minecraft:green_concrete_powder`, price: 4 },
            { id: `minecraft:cyan_concrete_powder`, price: 4 },
            { id: `minecraft:light_blue_concrete_powder`, price: 4 },
            { id: `minecraft:blue_concrete_powder`, price: 4 },
            { id: `minecraft:purple_concrete_powder`, price: 4 },
            { id: `minecraft:magenta_concrete_powder`, price: 4 },
            { id: `minecraft:pink_concrete_powder`, price: 4 },
            { id: `minecraft:glass`, price: 4 },
            { id: `minecraft:white_stained_glass`, price: 6 },
            { id: `minecraft:light_gray_stained_glass`, price: 6 },
            { id: `minecraft:gray_stained_glass`, price: 6 },
            { id: `minecraft:black_stained_glass`, price: 6 },
            { id: `minecraft:brown_stained_glass`, price: 6 },
            { id: `minecraft:red_stained_glass`, price: 6 },
            { id: `minecraft:orange_stained_glass`, price: 6 },
            { id: `minecraft:yellow_stained_glass`, price: 6 },
            { id: `minecraft:lime_stained_glass`, price: 6 },
            { id: `minecraft:green_stained_glass`, price: 6 },
            { id: `minecraft:cyan_stained_glass`, price: 6 },
            { id: `minecraft:light_blue_stained_glass`, price: 6 },
            { id: `minecraft:blue_stained_glass`, price: 6 },
            { id: `minecraft:purple_stained_glass`, price: 6 },
            { id: `minecraft:magenta_stained_glass`, price: 6 },
            { id: `minecraft:pink_stained_glass`, price: 6 },
            { id: `minecraft:mushroom_stem`, price: 6 },
            { id: `minecraft:red_mushroom_block`, price: 6 },
            { id: `minecraft:brown_mushroom_block`, price: 6 },
            { id: `minecraft:obsidian`, price: 2000 },
        ],
        lv: 0
    },
    /*{
        name: `建材`,
        lore: `building material`,
        icon: `minecraft:oak_log`,
        items: [
        ],
        lv: 30
    },*/
    /*{
        name: `食べ物`,
        lore: `food`,
        icon: `minecraft:bread`,
        items: [
            { id: `mc:onion`, price: 100 },
            { id: `mc:garlic`, price: 600 },
            { id: `mc:ovlive`, price: 750 },
            { id: `mc:tomato`, price: 750 },
            { id: `mc:mikan`, price: 300 },
            { id: `mc:adzuki_beans`, price: 200 },
            { id: `mc:sweet_corn`, price: 100 },
            { id: `mc:pineapple`, price: 1000 },
            { id: `mc:straw_berry`, price: 620 },
            { id: `mc:mikan`, price: 700 },
            { id: `mc:xmas_chicken`, price: 1500 },
            { id: `mc:pizza`, price: 2000 },
            { id: `mc:osechi`, price: 2200 },
            { id: `mc:omochi`, price: 500 },
           
        ],
        lv: 50
    },*/
    /*{
        name: `スポーンエッグ`,
        lore: `spawn egg`,
        icon: `minecraft:villager_spawn_egg`,
        items: [
            { id: `minecraft:blaze_spawn_egg`, price: 500 },
            { id: `minecraft:wither_skeleton_spawn_egg`, price: 800 },
            { id: `minecraft:magma_cube_spawn_egg`, price: 400 },
            { id: `minecraft:ghast_spawn_egg`, price: 400 },
            { id: `minecraft:zombie_pigman_spawn_egg`, price: 400 },
            { id: `minecraft:zoglin_spawn_egg`, price: 400 },
            { id: `minecraft:strider_spawn_egg`, price: 400 },
            { id: `minecraft:piglin_spawn_egg`, price: 400 },
            { id: `minecraft:piglin_brute_spawn_egg`, price: 1500 },
        ]
    },
    {
        name: `モブドロップ`,
        lore: `mob drop item`,
        icon: `minecraft:bone`,
        items: [
            { id: `minecraft:blaze_rod`, price: 300 },
            { id: `minecraft:magma_cream`, price: 300 },
            { id: `minecraft:shulker_shell`, price: 600 },
        ]
    },*/
    /*{
        name: `農業`,
        lore: `agriculture`,
        icon: `minecraft:carrot`,
        items: [
            { id: `mc:rice_seed`, price: 25 },
            { id: `minecraft:beetroot_seeds`, price: 25 },
            { id: `minecraft:pumpkin_seeds`, price: 25 },
            { id: `minecraft:melon_seeds`, price: 25 },
            { id: `mc:soybeans`, price: 50 },
            { id: `minecraft:cherry_sapling`, price: 5000 },
            { id: `minecraft:acacia_sapling`, price: 5000 },
            { id: `minecraft:birch_sapling`, price: 5000 },
            { id: `minecraft:dark_oak_sapling`, price: 5000 },
            { id: `minecraft:jungle_sapling`, price: 5000 },
            { id: `minecraft:oak_sapling`, price: 5000 },
            { id: `minecraft:pale_oak_sapling`, price: 5000 },
            { id: `minecraft:spruce_sapling`, price: 5000 },
            { id: `minecraft:dandelion`, price: 100 },
            { id: `minecraft:poppy`, price: 100 },
            { id: `minecraft:blue_orchid`, price: 100 },
            { id: `minecraft:allium`, price: 100 },
            { id: `minecraft:azure_bluet`, price: 100 },
            { id: `minecraft:red_tulip`, price: 100 },
            { id: `minecraft:orange_tulip`, price: 100 },
            { id: `minecraft:white_tulip`, price: 100 },
            { id: `minecraft:pink_tulip`, price: 100 },
            { id: `minecraft:oxeye_daisy`, price: 100 },
            { id: `minecraft:cornflower`, price: 100 },
            { id: `minecraft:lily_of_the_valley`, price: 100 },
            { id: `minecraft:sunflower`, price: 100 },
            { id: `minecraft:lilac`, price: 100 },
            { id: `minecraft:rose_bush`, price: 100 },
            { id: `minecraft:peony`, price: 100 },
            { id: `minecraft:pink_petals`, price: 100 },
        ],
        lv: 70
    },*/
    {
        name: `鍛冶型`,
        lore: `smithing template`,
        icon: `minecraft:netherite_upgrade_smithing_template`,
        items: [
            { id: `minecraft:netherite_upgrade_smithing_template`, price: 3000 },
            { id: `minecraft:spire_armor_trim_smithing_template`, price: 50000 },
            { id: `minecraft:snout_armor_trim_smithing_template`, price: 50000 },
            { id: `minecraft:rib_armor_trim_smithing_template`, price: 50000 },
        ],
        lv: 0
    },
    /*{
        name: `その他`,
        lore: `other`,
        icon: `minecraft:netherrack`,
        items: [
            { id: `minecraft:quartz`, price: 1 },
            { id: `minecraft:warped_fungus`, price: 40 },
            { id: `minecraft:crimson_fungus`, price: 40 },
            { id: `minecraft:soul_soil`, price: 4 },
            { id: `minecraft:soul_sand`, price: 4 },
            { id: `minecraft:warped_nylium`, price: 4 },
            { id: `minecraft:crimson_nylium`, price: 4 },
            { id: `minecraft:netherrack`, price: 4 },
            { id: `minecraft:blackstone`, price: 4 },
            { id: `minecraft:basalt`, price: 10 },
            { id: `minecraft:ancient_debris`, price: 10000 },
            { id: `minecraft:sponge`, price: 100 },
            { id: `minecraft:glowstone`, price: 40 },
            { id: `minecraft:purpur_block`, price: 10 },
            { id: `minecraft:end_stone`, price: 4 },
            { id: `minecraft:prismarine`, price: 4 },
            { id: `minecraft:crimson_stem`, price: 6 },
            { id: `minecraft:warped_stem`, price: 6 },
            { id: `minecraft:sculk`, price: 500 },
            { id: `minecraft:sculk_catalyst`, price: 50 },
            { id: `minecraft:mycelium`, price: 400 },
        ]
    },*/
    {
        name: `その他`,
        lore: `other`,
        icon: `minecraft:torch`,
        items: [
            { id: `minecraft:scaffolding`, price: 50 },
            { id: `minecraft:torch`, price: 10 },
            { id: `minecraft:lantern`, price: 20 },
            { id: `minecraft:sea_lantern`, price: 20 },
            { id: `minecraft:glowstone`, price: 20 },
            { id: `minecraft:ochre_froglight`, price: 20 },
            { id: `minecraft:pearlescent_froglight`, price: 20 },
            { id: `minecraft:verdant_froglight`, price: 20 },
            { id: `minecraft:experience_bottle`, price: 500 },
            { id: `minecraft:pitcher_plant`, price: 500 },
            { id: `minecraft:torchflower`, price: 500 },
            { id: `minecraft:blue_ice`, price: 15 },
        ],
        lv: 0
    },
];
