name: Build mcaddon

permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install -g typescript

          npm install \
            @minecraft/server@stable \
            @minecraft/server-ui@stable \
            @minecraft/server-admin@stable \
            @minecraft/server-gametest@stable

      - name: Build scripts
        run: |
          rm -rf script

          tsc \
            --rootDir src \
            --outDir script \
            --target ES2020 \
            --module ESNext \
            --moduleResolution node \
            --removeComments false \
            --skipLibCheck

      - name: Zip pack from repo A
        run: |
          zip -r MakeCountryBehavior.zip . \
            -x ".git/*" \
               ".github/*" \
               "README.md" \
               "*.zip" \
               "*.mcpack" \
               "*.mcaddon" \
               "src/*" \
               "src/**" \
               "node_modules/*" \
               "node_modules/**" \
               "package.json" \
               "package-lock.json"

          mv MakeCountryBehavior.zip MakeCountryBehavior.mcpack

      - name: Checkout other repo
        uses: actions/checkout@v4
        with:
          repository: karonyt/MakeCountryResourcePack
          path: other
          token: ${{ secrets.OTHER_REPO_TOKEN }}

      - name: Zip pack from repo B
        run: |
          cd other

          zip -r MakeCountryResource.zip . \
            -x ".git/*" \
               ".github/*" \
               "README.md" \
               "*.zip" \
               "*.mcpack" \
               "*.mcaddon"

          mv MakeCountryResource.zip ../MakeCountryResource.mcpack

      - name: Create mcaddon
        run: |
          VERSION="${GITHUB_REF_NAME}"

          zip "MakeCountry-${VERSION}.zip" \
            MakeCountryBehavior.mcpack \
            MakeCountryResource.mcpack

          mv "MakeCountry-${VERSION}.zip" \
             "MakeCountry-${VERSION}.mcaddon"


      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: MakeCountry-${{ github.ref_name }}.mcaddon